### PR TITLE
Add exercise: sieve

### PR DESCRIPTION
**Pull request by andrej-makarov-skrt**

### CODE REVIEW

**Comment by SaschaMann** [comment]
`trues(limit)` instead of `fill(true, limit)` would work here as well. It creates a `BitArray` instead which uses less memory. Not really relevant for this exercise, though, but might be helpful to know.

Thanks for adding this exercise!

**Comment by andrej-makarov-skrt** [comment]
@SaschaMann I thought about BitArray, but went further without using it. Thank you!

**Comment by SaschaMann** [comment]
Could you adjust the indentation for this one, too? Thanks!

**Comment by andrej-makarov-skrt** [comment]
Done! Please check it out.

**Comment by SaschaMann** [comment]
Looks good, thank you.

**Pull request merged**
